- sopel_modules/github/formatting.py
- sopel_modules/github/github.py
- sopel_modules/github/webhook.py
Also updated the `git.io` shortlink fetcher to use HTTPS.
It's worth noting that the `web.post()` method in Sopel hasn't taken a `headers` kwarg for quite some time, so this module won't work with `sopel.web` any more.
> Switch to requests

- sopel_modules/github/formatting.py
- sopel_modules/github/github.py
- sopel_modules/github/webhook.py
Officially the name of the site is "GitHub", not "Github". In filenames, URLs, and so on, it makes sense to have this be lowercase, but the name of the site shouldn't be output to users without the capital H.
Also changed the internal name of the config section, but that won't affect existing users.
(Running through this find-and-replace really gave me the idea that Sopel needs a way for modules to just declare that all their output should have a given prefix. So many repetitions of `[GitHub]`!)
> Capitalize GitHub everywhere it makes sense to do so

- sopel_modules/github/github.py
Replaced `.help` etc. with formatted strings, since not all Sopel bots use `.` as their command prefix.
> Use help_prefix in example commands sent to channel

- sopel_modules/github/webhook.py
Adds in missing `()` at the end of `return c.fetchall`
:sob: @dgw broke it almost a year ago! :no_good_man: 
https://github.com/sopel-irc/sopel-github/blame/fee9b788739626b7fc976b8f69f2aca704930839/sopel_modules/github/webhook.py#L107
> fix: get_targets returned functions instead of channel list

- sopel_modules/github/formatting.py
The code assumes that a comment was created, so letting it handle edits (for example) just leads to silly output, like giving identical output twice in the same channel because someone forgot a link & edited fast.
> webhook: ignore issue_comment payloads that aren't "created"

- sopel_modules/github/formatting.py
It's just nice to see "merged pull request" in chat instead of wondering why a PR that was good to go got closed unmerged (when it really didn't).
> webhook: Differentiate closed & merged PRs

- sopel_modules/github/formatting.py
Suppresses notifications for edits, etc.
Literally #16 but for `pull_request_review_comment` events instead.
> webhook: ignore review comments when not "created"

- sopel_modules/github/formatting.py
`re.match` is anchored at the beginning of the string. While this could have been done by switching to `re.search`, I think this approach is clearer — more explicit about what values are expected, and which should be ignored by the plugin.
This should be considered a bugfix as well as an enhancement, because right now the plugin only gives one side of the story if someone closes and reopens a pull request (such as sopel-irc/sopel#1542 just was, to fix a Travis-CI issue). Someone watching the IRC feed of events only would not know the PR was still active, and might think it had been rejected based on the closure.
> webhook: Handle re-opening issues/PRs

- sopel_modules/github/formatting.py
- sopel_modules/github/github.py
Turns out that when someone comments via email, GitHub spits out a comment body containing just `\n` instead of `\r\n`. So by splitting issue/PR comments only on `\r\n`, we'd get a smushed-together mess only when someone commented by email—comments left via any browser on any platform would be fine.
The fix is straightforward: Any time we were using `.split('\r\n', 2)`, we just use `.splitlines()` instead. Index 0 of the resulting list is still going to be the first line.
Converted the commit-message handler also, even though those should (probably?) always be `\n`, just because it's better to be safe. Python handles all the newline sequences we could possibly need, so let's let it do the job for us.
> formatting: Use `splitlines()`

- sopel_modules/github/github.py
Sometimes a commit only touches one file, and I'm tired of seeing "changes in 1 files" out of this plugin.
> commit: properly pluralize (or don't) "files"

- sopel_modules/github/github.py
- sopel_modules/github/webhook.py
While the method has been deprecated for ages (since Willie 4?), it was only just recently "officially" marked as such in Sopel's master branch. Since using it after Sopel 7 comes out will produce a deprecation warning in Sopel's output, we should replace it.
This isn't super urgent, as this plugin's next (non-patch) version will drop _long_ before Sopel 7 is ready, but having it all set to merge is the goal here.
> Replace `SopelMemory.contains()` with `in` operator

- sopel_modules/github/formatting.py
Yet untested, but I'll merge this into the bot on `#sopel` at freenode so the next Sopel release will trigger it. Just want to make sure the output does what I think it will. (If I get ambitious, I'll manually fire some edited events at it from my own machine, since the Sopel project doesn't often use things like prereleases.)
> webhook: handle release events

- sopel_modules/github/formatting.py
Inspired by @half-duplex's tongue-in-cheek complaint on IRC.
I would have put this into 0.1.7 if it had come up in time, but I'm not planning to make a 0.1.8 release. So I guess this gets to wait until 0.2.0.
> formatting: Use Oxford comma in comma-ized arrays

- sopel_modules/github/formatting.py
GitHub doesn't list possible `state` values for the `review` object anywhere, but there's some weirdness around replies to PR review comment that this patch tries to handle.
Basically, a `commented` review with no body is just ignored, because an empty body means it _must_ have review comments that the existing handler will take care of when that event fires, separately. It's the only way to avoid getting two notifications in channel from the plugin whenever someone replies to a review comment, and comes at only the small expense of not firing off a review summary message to IRC if someone really does leave a `commented` review with only line notes and no top-level comment body.
> webhook: Handle PR reviews

- sopel_modules/github/formatting.py
- sopel_modules/github/github.py
- sopel_modules/github/webhook.py
It usually looks way better than three standalone periods, and we really should take full advantage of Sopel's Unicode support.
Put in 0.2.0 just in case it might break someone's workflow because they're using some obscure environment that somehow can't handle this thing that even Python 2 has supported for years. (Actually, it's because changing the output except to fix a bug smells to me like "more than a patch release".)
> Convert most `...`s to `…` (Unicode ellipsis)

- sopel_modules/github/formatting.py
Not sure if the 'draft' key is always present in the 'pull_request' object, or if GitHub will end up changing that API before finalizing the feature, so we'll use `.get()` on it for safety just in case.
> webhook: Handle draft PRs and ready_for_review action

- sopel_modules/github/github.py
The username and repo name regexes weren't exactly accurate. They allowed underscore (`_`) which GitHub will not, and did not accept dot (`.`) in repo names even though GitHub allows that. (This was discovered by posting a link to Sopel's website, whose repo is named `sopel.chat`, and noting that the GitHub module didn't handle it as expected.)
With a bit of Google searching and some tweaks, we should have much more robust URL matching now.
This has been running for almost two weeks in our "official" Sopel instance on freenode, FWIW.
> main: update regexes to match GitHub URL bits

- sopel_modules/github/formatting.py
Also centralizes comment-body shortening into a single function, instead of having identical code everywhere, since the logic is no longer a single line of code.
Definitely going to have some conflicts with PRs like #31. Will need to keep an eye on other PRs as they get merged to see if this one needs updating on top of them (i.e. if they add more places where comments are spit out onto IRC).
> formatting: ignore quoted text when shortening comments

- sopel_modules/github/github.py
Includes automatic migration, which we can leave in for the life of 0.2.x and then remove in 0.3.0. (Note to self: Create issue or preemptive PR for removing the migration after merging this.)
> Fix setting name: `secret` -> `client_secret`

- sopel_modules/github/formatting.py
Reads like an absurdist English sentence, almost as bad as the famous "Buffalo buffalo buffalo Buffalo buffalo…", but it works.
> formatting: fix handling empty lines in comment shortener

- sopel_modules/github/formatting.py
GitHub started sending a `milestone` object with both `milestoned` and `demilestoned` events at some point in the last few months. It appears that the `milestone` object is always the one that was added or removed, regardless of the new state of the `issue` object.
With this new object, we can provide the milestone name for BOTH adding and removing.
Addresses known omission from #35.
> formatting: provide name for `demilestoned` events too

- sopel_modules/github/formatting.py
A one-line comment with extra surrounding whitespace would trigger adding `[…]` to the "shortened" comment even if the line wasn't truncated. That's wrong.
> formatting: extra whitespace != truncated comment

- sopel_modules/github/webhook.py
I'm just a student trying to learn so I really want your feedback guys!
Thanks a lot!
> handle_auth_response: wrong secret and raise error

- sopel_modules/github/formatting.py
- sopel_modules/github/github.py
We now ignore lines that look like Markdown quotations (leading `>`), Markdown headings (one or more leading `#`), and HTML-style comments (leading `<!--`). None of these makes for a particularly useful snippet when sent to IRC, so we exclude them.
> Ignore HTML-style comments and Markdown headings in comment shortener

- sopel_modules/github/github.py
GitHub's API response for a commit handily includes a `commit` key with the raw author/committer data as displayed in Git, which we can use if the `author` is `null` at the GitHub level (i.e. no user matching the email address used in Git).
Fixes #55.
Demo comparing my production bot (running sopel-github 0.2.6) and test bot (running this patch):
```
<~dgw> https://github.com/sopel-irc/sopel/commit/30cddb270c0223db09f81a0cb7fc9f195ecfd0b3
<&Kaede> Unexpected error ('NoneType' object is not subscriptable) from dgw at 2020-02-02
02:46:30.988810. Message was:
https://github.com/sopel-irc/sopel/commit/30cddb270c0223db09f81a0cb7fc9f195ecfd0b3
<SopelTest> [GitHub] [sopel-irc/sopel] Michael Yanovich: initial commit | 10767 changes in
142 files
```
> github: handle null commit author w/fallback to Git data

- README.md
- requirements.txt
- sopel_modules/github/github.py
* Use Sopel 7's fixed `@url` decorator
* Drop manual management of URL callback functions (taken care of for us by the decorator)
* Bump required Sopel version range
* Update/tweak README
Using the `@url` decorator should fix #7 (or most of it) since Sopel performs a punctuation-trimming step on URLs before processing them. It'll also mean more than one issue/PR, user, or repo link can be handled per IRC line (a shortcoming of the `@rule` approach we used in Sopel 6.x, in which `@url` was unreliable—it wouldn't work if the built-in `url.py` plugin was disabled).
> Sopel 7 compatibility

- sopel_modules/github/github.py
`repo_info()` didn't have a `match` arg, so the URL decorator wouldn't work properly with it.
Also cleaned up unused `match` arg in `.gh` command function.
This is stuff that should have happened in #58 but got overlooked.
> github: fix repo URL handling

- sopel_modules/github/github.py
GitHub deprecated passing authorization via query parameters: https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/
HTTP Basic Auth is the way forward, and they ignored (so far; it's been a week) my support request asking if there would be a better way to accomplish this that didn't involve OAuth or personal tokens. If this too gets deprecated later, I'll be quite annoyed, as we don't WANT to authenticate as a specific user in this plugin.
Closes #60
> github: change API auth from query params to HTTP Basic

- sopel_modules/github/github.py
Switched to the new API, `bot.channels`, now that its issues from Sopel 6.x have been fixed in version 7.
> github: migrate deprecated `bot.privileges` access

- sopel_modules/github/github.py
- sopel_modules/github/webhook.py
The proverbial `bot.msg()` has been deprecated since Sopel 6. In Sopel 7, using it emits warnings to the log. It's time we modernized how this plugin talks.
> Replace deprecated calls to `msg()` with `say()`

- sopel_modules/github/formatting.py
As the comments say, if a label is deleted, GitHub will send 'unlabeled' events for every issue/PR that had the deleted label, but the 'label' object won't be included. Rather than emit a placeholder ('[unknown label]' or something like that), skip these events. They can be pretty spammy anyway, if a label used on many issues/PRs is deleted.
I'd love to implement this in a neater way, but I think the whole `formatting` submodule needs a rewrite to make that possible.
> formatting: skip label/unlabel events without label in payload

- sopel_modules/github/github.py
I have no idea why this was using a fallback to group 1 (the command name) instead of just detecting an empty/missing group 2 (or 3).
Now instead of a generic "Not found" error for missing argument, caused by looking for a repo at `<nick>/<command_name>`, we have a proper usage reply and an example decorator.
> github: fix trigger groups in `.gh` command

- sopel_modules/github/webhook.py
The bot runs plugin `shutdown`s on disconnect from the IRC server. While
this method stops serving requests it doesn't actually close the socket; 
thus, the "restarted" webserver cannot bind to the same host/port in order 
to listen+serve requests. This results in a `OSError: [Errno 98] Address 
already in use`. The server needs to be closed after `shutdown`.
**edit**: As of this commit, the fix is valid for _all supported_ Python ~~>=2.7,>=3.5~~.
> webhook: fix error on reconnect

- sopel_modules/github/formatting.py
I dislike using the presence of certain dict keys to guess whether an issue was natively created vs. transferred in, but GitHub ties my hands on that. There's also no workaround for determining who actually transferred the incoming issue; that data just _isn't included_.
At least issues transferred _out_ have a distinct "action" type and proper "sender" info, thankfully…
_[As an aside: The more features that get added to the webhook handler here, the more obvious it is that GitHub's webhook payloads are not very well thought-out in places, especially when newer site features from the last few years are involved.]_
> webhook: Handle issue transfers

- sopel_modules/github/formatting.py
Bless GitHub for adding the ability to change your mind about a PR being ready for review, but of course it does require handling in this plugin to show up in activity feeds.
Hopefully this won't cause any merge conflict with #69, which I forgot about until now.
> formatting: handle 'converted_to_draft' PR event

- sopel_modules/github/formatting.py
@cottongin Does this adequately address #71 for you?
> formatting: abbreviate commit SHAs in `fmt_short_comment_body()`

- sopel_modules/github/formatting.py
New utility function `get_issue_or_pr_title()` because of course GitHub can't just give us one place to get fields that are common to all issues including pull requests. Let's only use it when necessary…
I'll say this resolves #52, and let @half-duplex complain in a new issue (or #25) if I missed any spots. 😛
> formatting: include title in assignee, label, & milestone webhooks

- sopel_modules/github/formatting.py
Tin. Pretty big diff for a tiny little change, and I really want to refactor the code now. Don't have time to do it, but I want to.
Note: Needs a formal test before merging, if I'm not too lazy.
> formatting: fix double space in webhook output for self-assignments

- sopel_modules/github/github.py
Closes #84. This was _trivial_ compared to what I thought I'd have to do (mess with the `formatting` submodule). Fancy having everything I needed already there in the `issue_info()` function…
> github: output link for numeric issue/PR references

- sopel_modules/github/github.py
Fetches the Pull endpoint if the referenced issue is a pull request AND ALSO has the 'closed' state, to check if it was merged.
Closes #86.
**Example:**
```
<Old> [GitHub] [sopel-irc/sopel #2020] half-duplex: logging: don't crash if backend is uninitialized | When
`core.logging_channel` is used, errors early in startup cause an exception that halts the bot.
(bdc10e0, current master) […]
<New> [GitHub] [sopel-irc/sopel #2020] merged PR by half-duplex: logging: don't crash if backend is
uninitialized | When `core.logging_channel` is used, errors early in startup cause an exception that
halts the bot. (bdc10e0, current master) […]
```
@half-duplex I like this style better than adding more brackets. What say you?
> github: include issue/PR state in `issue_info()`

- sopel_modules/github/github.py
Trending, events, collections, etc. are not real users and generate "Not Found" if their URLs happen to match the format of e.g. a repo URL. We can skip them and let the built-in title plugin do it.
Resolves #96.
> github: skip URL handling for links under special site sections

- sopel_modules/github/github.py
More proof that @xnaas should work in QA.
> github: repo names can in fact contain underscores

- sopel_modules/github/formatting.py
The undefined variable name was particularly bad. Guess nobody uses the single feature that relies on the broken function.
> formatting: lint cleanup

- sopel_modules/github/formatting.py
- sopel_modules/github/github.py
It hasn't been doing anything useful for a while anyway, since GitHub killed off their git.io shortening service.
Now that we definitely expect the full link, the `.gh-hook` command will output the authorization URL on its own line, with `max_messages` set to allow Sopel to split it across multiple messages if needed. Truncation would be very bad in that case.
Resolves #102.
> formatting: remove `shorten_url()`

- sopel_modules/github/github.py
Fixed TypeError on calling `.gh-repo` in a channel with no linked repo.
Added special `!clear` value to delete the linked repo without mucking around in sqlite3 CLI.
Generally improved output of the command.
_Yes, I know this is going to cause myself merge-conflict problems in #110._
> github: fix/improve `.gh-repo` command

- sopel_modules/github/github.py
Tin. Resolves #90.
Not necessary for webhooks, because commit output there is always in response to a push (meaning the commits are fresh, with very rare exceptions).
> github: output relative committer & author date for commit URLs

- README.md
- sopel_modules/github/formatting.py
use language='alias' instead of use_aliases=True, which was deprecated in 1.7.0,
see also: https://github.com/carpedm20/emoji/blob/v1.7.0/emoji/core.py
Pretty straight forward change. Let me know if there is anything else that I can/should do, since I already have the fork open.
> formatting: use `emoji` 2.0 style

- sopel_modules/github/formatting.py
After pushing v0.4.7 and SSHing into the main Sopel instance for Libera (to update the plugin there), I saw that the console log showed a KeyError for `base_ref_name` in the push handler. Lo and behold, GitHub's webhook documentation makes no mention of that or the `ref_name` field.
It's clearly been a while since this code was touched (sometime before Max split things into multiple files). Consulting Wayback Machine caches of the old developer.github.com doesn't actually show me any payload examples with the field names that were in the code here. Maybe this stuff was always broken, and no one noticed because hardly anyone:
1) uses webhooks; and
2) sends Sopel the push event type
That's my guess. This is an obscure feature of the plugin, certainly.
**Still to do:**
- proper testing
- …
> formatting: fix ref field names

- README.md
- setup.py
Declaring the `emoji` package as a setuptools extra means that the user only needs to install this plugin with that extra specified, & pip will take care of making sure they have the necessary dependency version.
This will help us avoid future occurrences like #118. The maintainer of `emoji` seems to be responsible about holding breaking API changes until the next major version, so I feel safe with the `emoji>=1.7,<3` range.
> build: `emoji` is now a setuptools extra, making it easier to install

- sopel_modules/github/github.py
https://docs.github.com/en/rest/overview/api-versions#about-api-versioning
This is for future-proofing. Occasionally the plugin's been broken by API changes that we weren't prepared for (I, at least, am not very good about keeping on top of announcements), and this way we are explicitly declaring which version we want and gaining a 24-month grace period to adapt after a new version is released.
> github: send API version header

- sopel_modules/github/github.py
Long replaced by `client_secret`, along with slightly janky (because it auto-rewrites Sopel's config file, erasing comments) auto-migration code to move the old `secret` value to the new place where it belongs.
Was meant to be removed in 0.3.0, but we went through the whole 0.4.x series with this still present.
> github: remove obsolete `secret` setting

- sopel_modules/github/github.py
`merged_at` is `null` if the PR is either open, or closed unmerged.
Not 100% certain that field is guaranteed to be populated for *every* PR on GitHub, regardless of age, but I think it's acceptable to get rid of the second API request in exchange for a small risk of giving slightly incorrect output in a very small number of cases.
> github: simplify getting PR merge status

- sopel_modules/github/github.py
This accepts `user/reponame#123` in all cases.
As before, if the current channel has a default repo (set using the `.gh-repo` command), `#123` will be treated as a reference to an issue or PR in the configured default repo. Additionally, `reponame#123` will now fill in the missing "username" portion from the configured default.
Implementing this feature required switching to named capture groups in all URL patterns, because the `user` and `reponame` portions of the inline references are optional. It seemed like a maintainability win, anyway, so even if I just missed thinking of a way to do it with numbered capture groups, I'm glad to have made the change anyway.
> github: support inline references to issues/PRs in any repo

- sopel_modules/github/github.py
Little bit janky, more of a test than a final implementation. This really illustrates what I meant in https://github.com/sopel-irc/sopel-github/issues/121#issuecomment-1491114633 when I said the real challenge would be making the message format flow nicely.
_Will_ close #121 when finished…
> github: timestamp for issue/PR (+comment) output

- sopel_modules/github/github.py
An easy solution to #127, though not as nuanced as the original intent. The granular approach should probably be part of this plugin's long-overdue refactoring; it'll probably be easier to do after we comb out the spaghetti code.
> github: suppress errors in `issue_info()` for invalid inline refs

- README.md
- sopel_modules/github/github.py
Resolve #131, including a new config setting to override the mitigation if so desired.
The new config value is intentionally omitted from `configure()`, since for most users the default will be fine and it would be more confusing to try to explain the setting's purpose in a one-line prompt.
As it says in #131, a per-channel option might be helpful in the long term. But like I wrote in #136, more granular/nuanced controls for things will be easier to do after the plugin is de-spaghettified (long overdue work).
> github: add config & logic to skip too-short inline issue numbers
